### ISSUE TITLE
Using i2cssh not working on ruby 2.4.3

### ISSUE THREAD

**Issue by Eagllus** [wouterdebie/i2cssh#81]
I follow the directions to install i2cssh and get the following error when trying to use it.

```
 ~> i2cssh --version
/usr/local/var/rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.2/lib/_aem/codecs.rb:236: warning: constant ::Fixnum is deprecated
/usr/local/var/rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.2/lib/_aem/codecs.rb:236: warning: constant ::Bignum is deprecated
/usr/local/var/rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/i2cssh-1.16.0/bin/i2cssh:80:in `<top (required)>': undefined method `inject' for nil:NilClass (NoMethodError)
	from /usr/local/var/rbenv/versions/2.4.3/bin/i2cssh:23:in `load'
	from /usr/local/var/rbenv/versions/2.4.3/bin/i2cssh:23:in `<main>'
```
