### ISSUE TITLE
v0.2.0 doesn't work with fish shell on macOS Sequoia 15.2

### ISSUE THREAD

**Issue by dounokouno** [wouterdebie/i2cssh#146]
**Describe the bug**

I executed the following command. The error message will be displayed after the attached screenshot.

```console
$ i2cssh -l user_name {ip_address1} {ip_address2} {ip_address3}
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/i2cssh/0.2.0/libexec/lib/python3.13/site-packages/iterm2/connection.py", line 420, in async_connect
    return await coro(self)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/i2cssh/0.2.0/libexec/lib/python3.13/site-packages/iterm2/connection.py", line 228, in async_main
    result = await coro(connection)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/i2cssh/0.2.0/libexec/lib/python3.13/site-packages/i2cssh/lib.py", line 361, in inner
    pane = window.current_tab.current_session
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'current_tab'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/i2cssh/0.2.0/libexec/lib/python3.13/site-packages/iterm2/connection.py", line 182, in _async_dispatch_forever
    data = await self.websocket.recv()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/i2cssh/0.2.0/libexec/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 554, in recv
    await self.ensure_open()
  File "/opt/homebrew/Cellar/i2cssh/0.2.0/libexec/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1005 (no status received [internal])
```

**Screenshots or stack traces**

<img width="892" alt="スクリーンショット 2024-12-20 13 12 49" src="https://github.com/user-attachments/assets/7a13197e-574a-4b85-9833-70968f8a6ecd" />

**Additional context**

I'm using macOS Sequoia 15.2 on an M3 MacBook Pro.

---

Please confirm it.

**Comment by wouterdebie** [comment]
Is fish in your path? What happens if you manually execute `/usr/bin/env
fish`?

**Comment by dounokouno** [comment]
I have confirmed that it works without any problems with i2cssh v0.2.1. Thank you for your help.
